[versions]
agp = "8.8.0"
appcompat = "1.7.0"
circleimageview = "3.1.0"
collapsingtoolbarlayoutSubtitle = "1.5.0"
constraintlayout = "2.2.0"
converterGson = "2.11.0"
dotsindicator = "5.1.0"
firebaseAuth = "23.1.0"
firebaseBom = "33.7.0"
firebaseDatabase = "21.0.0"
firebaseFirestore = "25.1.1"
firebaseMessaging = "24.1.0"
firebaseMessagingDirectboot = "24.1.0"
googleAuthLibraryOauth2Http = "1.3.0"
googleServices = "4.4.2"
gson = "2.11.0"
kotlinBom = "1.9.24"
material = "1.12.0"
navigationFragment = "2.8.5"
playServicesLocation = "21.3.0"
playServicesMaps = "19.0.0"
retrofit = "2.11.0"
viewpager2 = "1.1.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
collapsingtoolbarlayout-subtitle = { module = "com.hendraanggrian.material:collapsingtoolbarlayout-subtitle", version.ref = "collapsingtoolbarlayoutSubtitle" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-messaging-directboot = { module = "com.google.firebase:firebase-messaging-directboot", version.ref = "firebaseMessagingDirectboot" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }